from typing import Protocol, runtime_checkable


@runtime_checkable
class ForgeClient(Protocol):
    async def get_issue(self, issue_iid: int) -> dict: ...

    async def get_issue_comments(self, issue_iid: int) -> list[dict]: ...

    async def update_issue_description(self, issue_iid: int, description: str) -> None: ...

    async def set_labels(self, issue_iid: int, labels: list[str]) -> None: ...

    async def post_comment(self, issue_iid: int, body: str) -> dict: ...

    async def get_file_content(self, path: str, ref: str = "main") -> str: ...

    async def list_repository_tree(self, ref: str = "main") -> list[dict]: ...

    async def branch_exists(self, branch_name: str) -> bool: ...

    async def create_branch(self, branch_name: str, ref: str = "main") -> None: ...

    async def create_or_update_file(
            self, path: str, content: str, branch: str, commit_message: str
    ) -> None: ...
